# Generated by Django 4.2.28 on 2026-07-10 19:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('spine', 'Response spine'), ('phrase_prod', 'Phrase — production'), ('phrase_recog', 'Phrase — recognition')], max_length=16)),
                ('state', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('review', 'Review'), ('relearning', 'Relearning')], default='new', max_length=12)),
                ('due', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('interval_days', models.FloatField(default=0.0)),
                ('ease', models.FloatField(default=2.5)),
                ('reps', models.PositiveIntegerField(default=0)),
                ('lapses', models.PositiveIntegerField(default=0)),
                ('learning_step', models.PositiveSmallIntegerField(default=0)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('last_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('suspended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'families',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PhraseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'phrase categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_cards_per_day', models.PositiveIntegerField(default=15)),
                ('max_reviews_per_day', models.PositiveIntegerField(default=200)),
            ],
            options={
                'verbose_name_plural': 'settings',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=64)),
                ('order', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('emoji', models.CharField(default='📘', max_length=8)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'Again'), (2, 'Hard'), (3, 'Good'), (4, 'Easy')])),
                ('state_before', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('review', 'Review'), ('relearning', 'Relearning')], max_length=12)),
                ('state_after', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('review', 'Review'), ('relearning', 'Relearning')], max_length=12)),
                ('interval_before', models.FloatField(default=0.0)),
                ('interval_after', models.FloatField(default=0.0)),
                ('ease_before', models.FloatField(default=2.5)),
                ('ease_after', models.FloatField(default=2.5)),
                ('elapsed_ms', models.PositiveIntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='study.card')),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_hash', models.CharField(max_length=32, unique=True)),
                ('prompt', models.TextField(help_text='Canonical prompt text.')),
                ('reformulation', models.TextField(blank=True)),
                ('position', models.TextField(blank=True)),
                ('position_claire', models.TextField(blank=True)),
                ('nuance', models.TextField(blank=True)),
                ('conclusion', models.TextField(blank=True)),
                ('body', models.TextField()),
                ('body_html', models.TextField()),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='study.family')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='study.theme')),
            ],
            options={
                'ordering': ['theme__order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('is_canonical', models.BooleanField(default=False)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='study.family')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='study.response')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='study.theme')),
            ],
            options={
                'ordering': ['theme__order', 'number'],
                'unique_together': {('theme', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase_id', models.CharField(max_length=16, unique=True)),
                ('english_cue', models.CharField(max_length=200)),
                ('expression', models.CharField(max_length=300)),
                ('anchor', models.CharField(max_length=300)),
                ('example', models.TextField()),
                ('note', models.TextField(blank=True)),
                ('sources_raw', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='study.phrasecategory')),
                ('source_prompts', models.ManyToManyField(blank=True, related_name='phrases', to='study.prompt')),
            ],
            options={
                'ordering': ['order', 'phrase_id'],
            },
        ),
        migrations.AddField(
            model_name='card',
            name='phrase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='study.phrase'),
        ),
        migrations.AddField(
            model_name='card',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='study.response'),
        ),
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('idea', models.TextField()),
                ('developpement', models.TextField(blank=True)),
                ('exemple', models.TextField(blank=True)),
                ('consequence', models.TextField(blank=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arguments', to='study.response')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['state', 'due'], name='study_card_state_03c563_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['card_type'], name='study_card_card_ty_91a21b_idx'),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('phrase__isnull', True), ('response__isnull', False)), models.Q(('phrase__isnull', False), ('response__isnull', True)), _connector='OR'), name='card_has_exactly_one_target'),
        ),
        migrations.AlterUniqueTogether(
            name='argument',
            unique_together={('response', 'order')},
        ),
    ]
