# Generated by Django 4.2.28 on 2026-07-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_exampart_task_theme_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewlog',
            name='card_before',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
