# Generated by Django 4.2.28 on 2026-07-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_reviewlog_card_before'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='sources_raw',
            field=models.TextField(blank=True),
        ),
    ]
