# Generated by Django 4.2.28 on 2026-07-13 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_alter_phrase_sources_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='needs_revisit',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='revisit_added_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='study.card')),
            ],
        ),
    ]
