# Generated by Django 4.2.28 on 2026-07-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_card_needs_revisit_card_revisit_added_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsession',
            name='presentation_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='reviewsession',
            name='revisit_seen_card_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
