# Generated by Django 4.2.28 on 2026-07-15 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0007_loginthrottle_card_user_reviewlog_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsession',
            name='previous_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='study.card'),
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('note', 'Note'), ('highlight', 'Highlight')], max_length=12)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('body', models.TextField(blank=True)),
                ('quote', models.TextField(blank=True)),
                ('source_path', models.CharField(blank=True, max_length=500)),
                ('source_title', models.CharField(blank=True, max_length=300)),
                ('start_offset', models.PositiveIntegerField(blank=True, null=True)),
                ('end_offset', models.PositiveIntegerField(blank=True, null=True)),
                ('prefix', models.CharField(blank=True, max_length=160)),
                ('suffix', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='study.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_annotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['user', 'task', 'kind', 'updated_at'], name='study_annot_user_id_4aeae3_idx'), models.Index(fields=['user', 'source_path', 'kind'], name='study_annot_user_id_bf5976_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='annotation',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'highlight')), fields=('user', 'source_path', 'start_offset', 'end_offset'), name='unique_user_page_highlight'),
        ),
    ]
