# Generated by Django 5.2.16 on 2026-07-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0013_personalresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='study_later',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
