# Generated by Django 5.2.16 on 2026-07-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0014_annotation_study_later'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentImportState',
            fields=[
                ('key', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(max_length=64)),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
