# Generated by Django 5.2.16 on 2026-07-15 23:22

from django.db import migrations, models


def preserve_phrase_order(apps, schema_editor):
    Phrase = apps.get_model("study", "Phrase")
    Phrase.objects.update(lot_order=models.F("order"))


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0015_content_import_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='lot_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='phrase',
            name='tier',
            field=models.CharField(choices=[('shared', 'Shared catalog'), ('response', 'Response vocabulary')], db_index=True, default='response', max_length=8),
        ),
        migrations.RunPython(preserve_phrase_order, migrations.RunPython.noop),
    ]
