# Generated by Django 5.2.16 on 2026-07-16 23:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0017_reset_phrase_batch_sessions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprehensionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_key', models.CharField(max_length=120, unique=True)),
                ('number', models.PositiveSmallIntegerField()),
                ('passage_fr', models.TextField()),
                ('passage_en', models.TextField(blank=True)),
                ('prompt_fr', models.TextField()),
                ('prompt_en', models.TextField(blank=True)),
                ('correct_explanation', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['test__order', 'number'],
            },
        ),
        migrations.CreateModel(
            name='ComprehensionTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('expected_question_count', models.PositiveSmallIntegerField(default=36)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['order', 'number'],
            },
        ),
        migrations.CreateModel(
            name='ComprehensionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'En cours'), ('completed', 'Terminé'), ('abandoned', 'Abandonné')], db_index=True, default='in_progress', max_length=16)),
                ('current_question', models.PositiveSmallIntegerField(default=1)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_questions', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprehension_attempts', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='study.comprehensiontest')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ComprehensionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('text_fr', models.TextField()),
                ('text_en', models.TextField(blank=True)),
                ('rationale', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='study.comprehensionquestion')),
            ],
            options={
                'ordering': ['letter'],
            },
        ),
        migrations.CreateModel(
            name='ComprehensionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='study.comprehensionattempt')),
                ('selected_choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_answers', to='study.comprehensionchoice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_answers', to='study.comprehensionquestion')),
            ],
            options={
                'ordering': ['question__number'],
            },
        ),
        migrations.AddField(
            model_name='comprehensionquestion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='study.comprehensiontest'),
        ),
        migrations.AddConstraint(
            model_name='comprehensionchoice',
            constraint=models.UniqueConstraint(fields=('question', 'letter'), name='unique_comprehension_question_choice'),
        ),
        migrations.AddConstraint(
            model_name='comprehensionchoice',
            constraint=models.CheckConstraint(condition=models.Q(('letter__in', ['A', 'B', 'C', 'D'])), name='valid_comprehension_choice_letter'),
        ),
        migrations.AddConstraint(
            model_name='comprehensionanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_comprehension_attempt_answer'),
        ),
        migrations.AddConstraint(
            model_name='comprehensionquestion',
            constraint=models.UniqueConstraint(fields=('test', 'number'), name='unique_comprehension_test_question'),
        ),
        migrations.AddIndex(
            model_name='comprehensionattempt',
            index=models.Index(fields=['user', 'test', 'status'], name='study_compr_user_id_29f09a_idx'),
        ),
        migrations.AddConstraint(
            model_name='comprehensionattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('user', 'test'), name='unique_active_comprehension_attempt'),
        ),
    ]
