# Generated by Django 5.2.16 on 2026-07-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0019_subject_vocabulary_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprehensionanswer',
            name='question_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
