# Generated by Django 5.2.16 on 2026-07-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0020_snapshot_comprehension_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprehensionattempt',
            name='content_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
