# Generated by Django 5.2.16 on 2026-07-18 18:19
#
# Schema-only: add Card.started_at and its index. The data backfill lives in
# 0026 so the index is created in its own transaction (PostgreSQL rejects
# CREATE INDEX in a transaction that still has pending trigger events from the
# backfill's bulk updates).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0024_standardize_skill_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="started_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
