# Generated by Django 5.2.16 on 2026-07-19
#
# Schema-only: keep direct response practice separate from Card.started_at,
# whose historical backfill also includes annotations and linked vocabulary.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0027_canonical_public_urls"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="response_practice_started_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
