# Generated by Django 5.2.16 on 2026-07-20 07:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0031_backfill_svg_icon_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryQuestionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_number', models.PositiveSmallIntegerField()),
                ('question_key', models.CharField(max_length=96)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_question_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['memory_number', 'completed_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'memory_number', 'question_key'), name='unique_memory_question_progress')],
            },
        ),
    ]
